extends: eslint:recommended

plugins: ['babel', 'react']

parser: 'babel-eslint'

env:
  es6: true
  browser: true
  node: true

parserOptions:
  ecmaFeatures:
    modules: true
    jsx: true

rules:
  quotes: [2, 'single']
  semi: [2, 'never']
  react/jsx-uses-vars: [2]
  react/jsx-uses-react: [2]
  babel/generator-star-spacing: [1]
  babel/new-cap: [1]
  babel/object-shorthand: [1]
  babel/arrow-parens: [1]
  babel/no-await-in-loop: [1]
  react/react-in-jsx-scope: [2]
