extends: ['eslint:recommended', 'plugin:react/recommended']

plugins: ['babel', 'react']

parser: 'babel-eslint'

env:
  es6: true
  browser: true
  node: true

parserOptions:
  ecmaFeatures:
    modules: true
    jsx: true

rules:
  quotes: ['error', 'single']
  semi: ['error', 'never']
  babel/generator-star-spacing: ['error']
  babel/new-cap: ['error', {capIsNewExceptions: ['Immutable.Map', 'Immutable.List', 'Immutable.Set', 'Immutable.OrderedSet', 'Immutable.OrderedMap']}]
  babel/object-shorthand: ['error']
  babel/arrow-parens: ['error']
  babel/no-await-in-loop: ['error']
  react/react-in-jsx-scope: ['error']
  react/no-find-dom-node: ['warn']
