extends: standard
plugins:
  - standard
env:
  es6: true
  jest: true
  browser: true
  jquery: true

plugins:
  - react

ecmaFeatures:
  jsx: true

rules:
  space-before-function-paren:  0
  indent: 0
  padded-blocks: 0
  operator-linebreak: 0
  no-extra-bind: 0
  quotes: 0
  no-unused-vars: 0
