// flow-typed signature: cd17ba9016b43af7844a725990484ce6
// flow-typed version: <<STUB>>/mocha-circleci-reporter_v0.0.2/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha-circleci-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha-circleci-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'mocha-circleci-reporter/index' {
  declare module.exports: $Exports<'mocha-circleci-reporter'>;
}
declare module 'mocha-circleci-reporter/index.js' {
  declare module.exports: $Exports<'mocha-circleci-reporter'>;
}
