// flow-typed signature: 426c4982ada785c42cdb3ef19cba5e38
// flow-typed version: <<STUB>>/modularscale-sass_v3.0.5/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'modularscale-sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'modularscale-sass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'modularscale-sass/eyeglass-exports' {
  declare module.exports: any;
}

// Filename aliases
declare module 'modularscale-sass/eyeglass-exports.js' {
  declare module.exports: $Exports<'modularscale-sass/eyeglass-exports'>;
}
