// flow-typed signature: 7e8aa35e5070de1b6a1659ca06658f0e
// flow-typed version: <<STUB>>/project-name-generator_v2.1.4/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'project-name-generator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'project-name-generator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'project-name-generator/spec/generator.spec' {
  declare module.exports: any;
}

declare module 'project-name-generator/spec/nouns-adjectives.spec' {
  declare module.exports: any;
}

declare module 'project-name-generator/spec/spec-helpers' {
  declare module.exports: any;
}

declare module 'project-name-generator/src/adjectives' {
  declare module.exports: any;
}

declare module 'project-name-generator/src/generator-bin' {
  declare module.exports: any;
}

declare module 'project-name-generator/src/generator' {
  declare module.exports: any;
}

declare module 'project-name-generator/src/nouns' {
  declare module.exports: any;
}

// Filename aliases
declare module 'project-name-generator/spec/generator.spec.js' {
  declare module.exports: $Exports<'project-name-generator/spec/generator.spec'>;
}
declare module 'project-name-generator/spec/nouns-adjectives.spec.js' {
  declare module.exports: $Exports<'project-name-generator/spec/nouns-adjectives.spec'>;
}
declare module 'project-name-generator/spec/spec-helpers.js' {
  declare module.exports: $Exports<'project-name-generator/spec/spec-helpers'>;
}
declare module 'project-name-generator/src/adjectives.js' {
  declare module.exports: $Exports<'project-name-generator/src/adjectives'>;
}
declare module 'project-name-generator/src/generator-bin.js' {
  declare module.exports: $Exports<'project-name-generator/src/generator-bin'>;
}
declare module 'project-name-generator/src/generator.js' {
  declare module.exports: $Exports<'project-name-generator/src/generator'>;
}
declare module 'project-name-generator/src/nouns.js' {
  declare module.exports: $Exports<'project-name-generator/src/nouns'>;
}
